### ISSUE TITLE
Reset BlankNode counter

### ISSUE THREAD

**Issue by jlanza** [rdf-ext/rdf-graph-array#1]
What do you think about reseting the counter whenever you want? There is no point in doing it when you start a graph as in case you add a graph to another it would have incorrect information. But sometimes you are creating unbound graphs and might be interesting.

**Comment by bergos** [comment]
I'm not sure if we should make this an official documented feature. Version 1.0.0 of RDF-Ext will implement [this spec](https://github.com/rdfjs/representation-task-force) and it will support [defining the blank node identifier](https://github.com/rdfjs/representation-task-force/issues/30).

At the moment it's already possible to reset the counter manually: `rdf.BlankNode.nextId = 0`

**Comment by jlanza** [comment]
Then I would take that option as I'm setting the annotator on a server, so the numbers will be increasing over the time ;)
